### ISSUE TITLE
--data does not work under some conditions

### ISSUE THREAD

**Issue by jacksongoode** [fitnr/taft#14]
Reviving #4 in a new issue.

Currently 
```
taft --data 'cool=true' source/page.hbs
cat data.json/yaml/ini | taft --data - source/page.hbs
```
does work but
```
taft --data '{"cool": true}' source/page.hbs
taft --data data.json/yaml/ini source/page.hbs
```
does not.

**Comment by fitnr** [comment]
What platform are you using? Could you post a minimal page.hbs example?

**Comment by jacksongoode** [comment]
Oh I used the exactl example descibred in #4. I'm on macOS.

**Comment by fitnr** [comment]
I was able to reproduce the bug and fix it by updating some older dependencies. I've published a new version (0.8.0), let me know if that works.

**Comment by jacksongoode** [comment]
Thanks! I'll let you know.

**Comment by jacksongoode** [comment]
Hmm, it seems there is still an issue.

test.hbs
```html
<a class="card"
{{#if urlTitle}}
    href="www.{{urlTitle}}.com"
{{/if}}>
```

test.json
```json
{
    "urlTitle": "hello"
}
```

Seems to still not produce the expected `www.hello.com` with `./node_modules/.bin/taft --data test.json test.hbs`

**Comment by fitnr** [comment]
As discussed in the [data](https://github.com/fitnr/taft#data) section of the README, files passed to `--data` can be accessed with  an object with the appropriate basename. Adjust your `test.hbs` to:
```html
<a class="card"
{{#if data.urlTitle}}
    href="www.{{data.urlTitle}}.com"
{{/if}}>
```

This rule is different for data passed in via stdin – those keys are available directly.

**Comment by jacksongoode** [comment]
Sorry @fitnr, but that change alone does not produce the expected result either. Is the base name of the parent directory the json is located within?

**Comment by jacksongoode** [comment]
Simple case:

```yaml
# data.yml
test: |
  <p>Hello</p>
```

Will not render in a template when passed as `-d data.yml...`
